[tool.poetry]
name = "otto-layout"
version = "0.0.4"
description = ""
authors = ["Herwin van Welbergen <h.vanwelbergen@otto.de>"]

[tool.poetry.dependencies]
python=">=3.8, <3.11"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
